### ISSUE TITLE
Help in local setup

### ISSUE THREAD

**Issue by milkovsky** [gossi/composer-localdev-plugin#8]
I have not managed to get it running locally.

I have installed the package:
```
$ composer global require 'gossi/composer-localdev-plugin=dev-master'
$ composer global update
```

I have a package "vendor-x/package-x".

I have a config file `~/.composer/config.json`:
```
{
  "config": {
    "localdev": {
      "": ["~/packages"],
      "vendor-x": "~/packages/vendor-x",
      "vendor-x/package-x": "~/packages/vendor-x/package-x"
    }
  }
}
```

I can see the config when I run `composer config --list --global`

My root composer file is placed in `/var/www/html`, my package is placed at `docroot/profiles/contrib/package-x/`. It is a Drupal 8 profile, but nevermind.

I can not see any changes when I execute `composer install` or `composer update vendor-x/package-x`. When I remove the package folder from ``docroot/profiles/contrib/package-x/`, it is cloned again from the original git repository and now symlinked from the local packages folder.

What am I doing worng? :)

**Comment by benr77** [comment]
I'm not sure if `~` is resolving to your homedir. Try with absolute paths first to get it working

**Comment by gossi** [comment]
The `config.json` looks good to me. Make sure your paths are correct. Also what @benr77 mentioned, you should check composer evaluates your  `~` correctly.

If you install/update a package that is handled by a custom installer, you probably have to run `composer install/update` twice in the project folder (a limitation by composer). Basically, the plugin tells you on the console output whether a package got symlinked (or already is).

To debug, you may want to put some echo statements into my code, which let you know, that your configuration is correct and paths are matched accordingly.

**Comment by milkovsky** [comment]
Thank you. Changing to `/root` from `~` helped.

**Comment by IllyaMoskvin** [comment]
I think this might be a macOS issue. I've run into similar things before.

For me, changing to `/Users/foobar` instead of `~` worked.

**Comment by milkovsky** [comment]
FYI I had this problem on Ubuntu.

**Comment by gossi** [comment]
Looks like a permission problem to me? Perhaps `composer` is not run as your user (maybe `php`?) or with a different environment, then all of those issues here are explained 😀

**Comment by milkovsky** [comment]
Thanks @gossi , the issue is closed and fixed. Your tip with path in https://github.com/gossi/composer-localdev-plugin/issues/8#issuecomment-339286450 helped.
